#!/bin/bash
LOG=/tmp/build.log

trap end_of_script 1 2 3 6 9 14 15

end_of_script () {
  [ -n "${1:-}" ] && EXIT="${1}" || EXIT=0
  [ -n "${2:-}" ] && echo "$2" >&2
  [ $EXIT -gt 0 ] && cat $LOG >&2
  exit $EXIT
}

cp -a /ssh /root/.ssh  >$LOG 2>&1

chown -R root:root /root/.ssh >$LOG 2>&1
chmod 700 /root/.ssh >$LOG 2>&1

for var in $*; do
    go get -fix -u $var  >$LOG 2>&1 || go get -u $var || end_of_script 1 "go get -fix -u $var"
done

go install -a ... >$LOG 2>&1 
cd /workspace/bin/ && tar -c *

